jobs:
- template: .azure-pipelines/windows.yml
  parameters:
    name: Windows
    vmImage: windows-2019
    matrix:
      py37-x86:
        PYTHON_VERSION: '3.7'
        PYTHON_ARCH: 'x86'
      py37-x64:
        PYTHON_VERSION: '3.7'
        PYTHON_ARCH: 'x64'
